<?php
module_load_include('access.inc', 'full_node_version');
module_load_include('admin.inc', 'full_node_version');
module_load_include('node_form.inc', 'full_node_version');
module_load_include('review.inc', 'full_node_version');
module_load_include('status.inc', 'full_node_version');
module_load_include('node_status.inc', 'full_node_version');
module_load_include('testing_state.inc', 'full_node_version');


// $Id: full_node_version.module,v 1.40 2008/02/27 15:32:05 robloach Exp $

define('DEBUG', false);
/*
 * implementation of hook_perms
 */
function full_node_version_perm() {
 return array (
   'full node version live',
   'full node version test',
   'full node version active',
   'full node version superseded',
   'administer full node version', 
   'administer full node version on nodes', 
   'review testing status',
 );
}
/**
 * Implementation of hook_menu() to add the admin section
 */
function full_node_version_menu() {
  $items = array();
  $items['admin/settings/full_node_version'] = array(
    'title' => 'Full Node Version',
    'page callback' => 'full_node_version_admin',
    'access arguments' => array('administer full node version'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/review_testing_status'] = array(
    'title' => 'Review Testing Status',
    'page callback' => 'full_node_version_testing_status',
    'access arguments' => array('review testing status'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/toggle-testing'] = array(
    'title' => 'Toggle Testing',
    'page callback' => 'full_node_version_toggle_testing',
    'access arguments' => array('review testing status'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['node/%/fnv_node_status']= array(
    'title' => t('Full Node Version Status'),
    'page callback' => 'full_node_version_node_status',
    'page arguments' => array(1),
    'access callback' => 'full_node_version_node_status_access',
    'access arguments' => array('review testing status',1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10
  );
  return $items;
}
/*
 * Implementation of hook_forms()
 */
function full_node_version_forms() {

  # the form id Drupal plans on using will be the first 
  # element of the first array.
  $args = func_get_args();
  $form_id = $args[0];
  $node = $args[1];

  $forms = array();
  if (strpos($form_id, "full_node_version_status_form") === 0) {
    $forms[$form_id] = array(
      'callback' => 'full_node_version_status_form',
      'callback arguments' => $node,
    );
  }
  return $forms;

}
  


